Add error handler or log error instead of using "continue" on exception in vSphere
StackStorm-Exchange/stackstorm-vsphere pull request #80
Opened 2021-03-08 11:45 UTC by shivani-orch

Replace the continue statement with explicit error logs. The pass/continue statement when run in production (non-debug) code will skip the error. We want to practice safe coding so exception handling is necessary.

2021-03-09 00:43 UTC, m4dcoder requested changes

2021-03-09 00:43 UTC, m4dcoder commented on actions/vm_snapshots_delete.py
> +                print(f'No snapshots found for VM. {e}')
Can you do `self._logger.exception(f'No snapshots found for VM.')` instead of print? Also since we are using logger.exception, there's no need to pass `e`.

2021-03-11 18:20 UTC, m4dcoder approved these changes

2021-03-11 18:20 UTC, merged

2021-03-11 18:49 UTC, nmaludy commented
@bishopbm1 is this going to break stuff?

2021-03-11 18:56 UTC, m4dcoder commented
@shivani-orch Can you add a version change in the pack yaml and an entry in the changelog?